{
  "formatVersion": "1.1",
  "component": {
    "group": "com.closure.plugin",
    "module": "closure-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "closure-plugin-1.0.0.jar",
          "url": "closure-plugin-1.0.0.jar",
          "size": 13412,
          "sha512": "5d0564df6c02e0c4471c99492fab3cbd211d6ea51b0543bfbbaf150d95709f60b2893dd5ac0f741cdcab5f92ac7f1e6ed5124513114a4f42fdd814e39d20b1f6",
          "sha256": "f961379d9d214dc1a684c8873032de7af24d5780b829d4ec26cbd2550fa47f1b",
          "sha1": "2877790644570e3c15bce7fcbd1f78eae3176513",
          "md5": "8355298ab716a852cf6dd91ee9c8b49d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "closure-plugin-1.0.0.jar",
          "url": "closure-plugin-1.0.0.jar",
          "size": 13412,
          "sha512": "5d0564df6c02e0c4471c99492fab3cbd211d6ea51b0543bfbbaf150d95709f60b2893dd5ac0f741cdcab5f92ac7f1e6ed5124513114a4f42fdd814e39d20b1f6",
          "sha256": "f961379d9d214dc1a684c8873032de7af24d5780b829d4ec26cbd2550fa47f1b",
          "sha1": "2877790644570e3c15bce7fcbd1f78eae3176513",
          "md5": "8355298ab716a852cf6dd91ee9c8b49d"
        }
      ]
    }
  ]
}
